### ISSUE TITLE
_parse_sentence may fail with an UnicodeError after a soft reboot

### ISSUE THREAD

**Issue by MSube** [adafruit/Adafruit_CircuitPython_GPS#19]
> Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "adafruit_gps.py", line 102, in update
  File "adafruit_gps.py", line 148, in _parse_sentence
UnicodeError: 

line 148: sentence = str(sentence, 'ascii').strip()
fails if sentence contains stale data that is not ascii.

**Comment by dherrada** [comment]
Can you check and see if this still happens? #21 should have fixed this
